# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8840ac8b4606318393b5c718e67e4ecad394cbadf7544af70bea490e0b036776a17f5b99e137805b2cec9a4cbb418def6b1d86fff30c76236ea83052d193581b

test:
  secret_key_base: 181005465935c252f2fbc1801d366ba13d270d77b64d5eca8a4c438ad2a3e2f3e4afc62d23054809421eb04748810e7be05d36b582e76b62ce371e036630845c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
